### PR TITLE
Unifications

### PR DESCRIPTION
**Pull request by Bost**
I unified the macros `defaxiom`, `defthm`, `deflemma` and a small part of the `example` into `handle-def-axiom-thm` and `handle-de`. The names are semi-randomly chosen. Change them as you please.

Except this I noticed a bunch of more redundancies popping up, so this might be a longer running development effort i.e. a git branch. Anyway, I think I reached a point where we can polish things up and merge them with the master branch. What do you think?

BTW I did the tests in the `latte-prelude`, `latte-integers` and `latte-sets` using this bash script:

```bash
#!/usr/bin/env bash

latte_central_dir="/path/to/latte-central"

projects=(
    latte-prelude
    latte-integers
    latte-sets
)
for prj in ${projects[@]}
do
    echo "cd ${latte_central_dir}/${prj}"
          cd ${latte_central_dir}/${prj}
    # increase project version
    sed --in-place 's/1.0b1-SNAPSHOT/1.0b2-SNAPSHOT/g' project.clj
    echo "lein do certify, codox, install"
          lein do certify, codox, install
    retCode=$?
    if [ $retCode -ne 0 ]; then
        echo "ERROR retCode: ${retCode}"
        break;
    fi
done
```

### CODE REVIEW

**Comment by fredokun** [comment]
Hi, thx for this PR it's quite deep... I need to review it and probably change a little bit the way the unification is made. DRY principle is important but code is not just "write-only", sometimes it is important to repeat oneself for the sake of readability. Generic code may reduce the possible occurrence of a bug, and reduce the code size, but it can also make the code hard to understand.

 One thing I consider very important is that the code must be readable from the point of view of the "proof assitant" domain.  For example there is a major conceptual difference between definitions on the one side and theorems/lemmas on the other side... Even if this involves some level of duplication I intend to keep separate the way they are to be handled.  However your PR goes in the right direction concerning the theorems/lemmas/axioms because these are variants of a similar concept : a mathematical truth statement. I still need to document clearly the very important distinction between an axiom and a theorem/lemma.  This is also a good time to reflect upon the error messages.

So in a soon to be created branch I will code something like an intermediate between what you propose and the current master. Even if I don't use directly your commits you will be credited as a collaborator for this important refactoring step.  I will also explain the core in the literal prog. way as I did with the kernel, this is good way to see if things are to be kept separate (because they need a separate explanation), or factored-out...

Thanks also for the bash script, maybe I should setup a CI process at some point.
(as long as the master does not reduce the redundancy I keep this branch open)

**Comment by fredokun** [comment]
Commit https://github.com/latte-central/LaTTe/commit/74b0972757179c0cfd062e5b4f40348b9c666bb1 addresses some of your refactoring suggestions. There is still a separation between `definition` on the one side and `defthm` etc. on the other side. I may refactor a little bit more but I am not decided yet, given the explanations I have added.  Note also that I enabled the `test` target because the core should be tested separately.  Thank you again for your PR it was very useful (even if I did not "unify" as you suggested). I close this PR for now.

**Comment by Bost** [comment]
I pulled the current master branch fd12495, here are my comments:

* Regarding the `defthm`, `deflemma`, `defaxiom`:
> Even if this involves some level of duplication I intend to keep separate the way they are to be handled.

I don't understand the reasons for the duplicity here. Please be more verbose.
What I see here is that the `definition`, `proof`, `example`, `defimplicit`, `defimplicit*`, `defnotation` are strikingly similar. It just screams to my eyes "Hey, we're (almost) all the same don't treat us (so) differently".

* definition vs. declaration: There are several places where it gets ambiguous. The best example is the 
`define-statement!` returning `[:declared ...]`

* Some comments are over-verbose. E.g.:
```clojure
    ;;{
    ;; and then we proceed with the main steps:
    ;;
    ;;  - Step 1: we parse the parameters (`params`) of the statement
    ;;}
    (let [[status params] (parse-parameters defenv/empty-env params)]
```

There's no added value in describing the function `parse-parameters` with ``we parse the parameters (`params`) of the statement``. The function name is descriptive enough. Besides, There's a difference (albeit small) between the developers intention and the implementation. This function knows nothing about any statements whatsoever.

Please don't get me wrong, but these things bother me a lot. I might be having some sort of Asperger syndrome or something... which in turn might come in handy when working on a thing called "**proof** assistant library" :) You decide...

Now one really important thing regarding lemmas and theorems:
I fail to understand the reasons for privacy of statements in LaTTe. Why a proven(!) statement can't be reusable and accessible from everywhere? Besides, and arguably more importantly, the `:private` flag is not used anywhere except the core_test.clj. See for yourself:
```bash
#!/usr/bin/env bash

latte_central_dir="/path/to/latte-central"

projects=(
    LaTTe
    latte-euroclojure-2016
    latte-finsets
    latte-integers
    latte-kernel
    latte-prelude
    latte-sets
    latte-tutorial
)
for prj in ${projects[@]}
do
    echo "cd ${latte_central_dir}/${prj}"
          cd ${latte_central_dir}/${prj}

    grep -nir ":private" --exclude-dir={.git} --include=\*.{clj,cljs,cljc} ./
done
```

**Comment by fredokun** [comment]
I see your point ... However  factoring out properly is not so easy IMHO. Maybe we agree on the symptoms but maybe not on the solution. And BTW it is good to be systematic about it (instead of a syndrome of some sort ;-).  And sorry also to be a little bit on the defensive side... For now I need to do some cleanup on the libs while I try to find some time for the tutorial. But I keep this in mind.

**Pull request closed without merging**
